require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "tmp/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
Bundler/OrderedGems:
  Enabled: false
Metrics/MethodLength:
  Max: 20
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Max: 50
RSpec/MultipleExpectations:
  Enabled: false
RSpec/BeEq:
  Enabled: false
